### PR TITLE
Add a `min-width` to popup

### PR DESCRIPTION
**Pull request by dimitarnestorov**
Quick win when running the app on macOS/iPadOS. Let me know if there's a more preferred styling approach. 320 is the width of the iPod touch 7th generation (the smallest iOS device that supports iOS 15).
|Before|After|
|-|-|
|Simulator Screen Shot - iPad mini (6th generation) - 2022-11-10 at 22 31 10|Simulator Screen Shot - iPad mini (6th generation) - 2022-11-10 at 22 25 22|
|image|image|

### CODE REVIEW

**Comment by dimitarnestorov** [comment]
So that's how you do it with Tailwind, I see.

**Comment by shunkakinoki** [comment]
Yes, haha, checking now on local

**Comment by shunkakinoki** [comment]
Screenshot 2022-11-11 at 12 41 19 PM

**Comment by shunkakinoki** [comment]
Perfect! Merging now

**Pull request merged**
